#!/bin/bash
# Upgrade forge harness from the template repository.
# Run from your project root after initial scaffold.
#
# Usage: ./.forge/scripts/upgrade.sh
#
# What it does:
#   1. Adds co-forge template as a git remote (if not already)
#   2. Fetches latest changes
#   3. Updates .claude/skills/ and .agents/skills/ (skill definitions)
#   4. Updates .forge/scripts/ (runtime scripts, preserves test_fast.sh)
#   5. Updates .forge/templates/ (project templates)
#
# What it does NOT touch:
#   - AGENTS.md, docs/, src/, tests/ (project-specific)
#   - docs/projects/ (project state)
#   - .forge/scripts/test_fast.sh (generated per tech stack)

set -e

# Cleanup temp files on unexpected exit
_upgrade_cleanup() {
  [ -n "${BACKUP_TEST:-}" ] && [ -f "${BACKUP_TEST:-}" ] && rm -f "$BACKUP_TEST"
  return 0
}
trap _upgrade_cleanup EXIT

TEMPLATE_REMOTE="template"
TEMPLATE_URL="https://github.com/kisuya/co-forge.git"

echo "=== Forge Upgrade ==="

# --- Step 1: Ensure template remote exists ---
if ! git remote get-url "$TEMPLATE_REMOTE" &>/dev/null; then
  echo "Adding template remote..."
  git remote add "$TEMPLATE_REMOTE" "$TEMPLATE_URL"
  echo "  ✓ Remote '$TEMPLATE_REMOTE' → $TEMPLATE_URL"
else
  CURRENT_URL=$(git remote get-url "$TEMPLATE_REMOTE")
  echo "  Template remote exists: $CURRENT_URL"
fi

# --- Step 2: Fetch latest ---
echo "Fetching template updates..."
git fetch "$TEMPLATE_REMOTE" --quiet
echo "  ✓ Fetched"

# --- Step 3: Check for changes in harness files ---
DIFF_FILES=$(git diff --name-only HEAD "$TEMPLATE_REMOTE/main" -- \
  .claude/skills/ \
  .agents/skills/ \
  2>/dev/null || true)

if [ -z "$DIFF_FILES" ]; then
  echo ""
  echo "=== Already up to date ==="
  exit 0
fi

echo ""
echo "Changed files:"
echo "$DIFF_FILES" | sed 's/^/  /'
echo ""

# --- Step 4: Update skills (source of truth) ---
echo "Updating .claude/skills/..."
git checkout "$TEMPLATE_REMOTE/main" -- .claude/skills/
echo "  ✓ Skills updated"

echo "Updating .agents/skills/..."
git checkout "$TEMPLATE_REMOTE/main" -- .agents/skills/
echo "  ✓ Symlinks updated"

# --- Step 5: Update runtime scripts (preserve test_fast.sh) ---
echo "Updating .forge/scripts/..."

# Backup test_fast.sh (project-specific, generated by scaffold)
BACKUP_TEST=""
if [ -f ".forge/scripts/test_fast.sh" ]; then
  BACKUP_TEST=$(mktemp)
  cp .forge/scripts/test_fast.sh "$BACKUP_TEST"
fi

# Copy updated scripts from skills source
SCRIPT_SRC=".claude/skills/forge-define/scripts"
for script in init.sh checkpoint.sh new_project.sh orchestrate.sh upgrade.sh; do
  if [ -f "$SCRIPT_SRC/$script" ]; then
    cp "$SCRIPT_SRC/$script" ".forge/scripts/$script"
  fi
done
chmod +x .forge/scripts/*.sh

# Restore test_fast.sh
if [ -n "$BACKUP_TEST" ] && [ -f "$BACKUP_TEST" ]; then
  cp "$BACKUP_TEST" .forge/scripts/test_fast.sh
  rm -f "$BACKUP_TEST"
fi
echo "  ✓ Runtime scripts updated (test_fast.sh preserved)"

# --- Step 6: Update templates ---
echo "Updating .forge/templates/..."
TEMPLATE_SRC=".claude/skills/forge-define/templates"
if [ -d "$TEMPLATE_SRC" ]; then
  cp "$TEMPLATE_SRC"/*.template .forge/templates/ 2>/dev/null
  echo "  ✓ Templates updated"
fi

# --- Step 7: Summary ---
echo ""
echo "=== Upgrade Complete ==="
echo ""
echo "Updated from template: $(git log "$TEMPLATE_REMOTE/main" --oneline -1)"
echo ""
echo "Review changes:"
echo "  git diff --cached    (staged changes)"
echo "  git diff             (unstaged changes)"
echo ""
echo "If everything looks good:"
echo "  git add -A && git commit -m 'Upgrade forge harness'"
